classes:
  - nsidc_miniconda

nsidc_miniconda::install:
  /opt/miniconda:
    version: '4.10.3'
    owner: vagrant
    group: vagrant
    build: true
    packages: []
    config:
      location: /home/vagrant
      channels:
        anaconda_nsidc_main: false
        anaconda_nsidc_dev: false
        conda_forge: true
